# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:            Ben's IT Diary
email:            i@seedme.app
description:      Keep it neat
baseurl:          '' # The subpath of your site, e.g. /blog
url:              'https://ben.seedme.app' # The base hostname & protocol for your site
github_username:  benjaminv
twitter_username: benuoa

markdown:  kramdown
permalink: pretty
paginate:  12

plugins:
  - jekyll-paginate
  - jekyll/tagging

include:
  - _pages

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock

sass:
  style: compressed

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

# Pages path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

# Authors
authors:
  ben:
    name:             Ben Hu
    bio:              A web App developer and a cloud infrastructure enthusiast. Formerly a petroleum geologist.
    gravatar:         https://s.gravatar.com/avatar/f456bb14ac63f83dc58bcd02b5ed84bb?s=150
    email:            i@seedme.app
    website:          https://ben.seedme.app
    github_username:  benjaminv
    twitter_username: benuoa